export const STORE = {
  name: "Elegant Touch",
  tagline: "إكسسوارات ومجوهرات مختارة بعناية",
  whatsapp: "201557637446",
  instagram: "https://www.instagram.com/elegant.touch33/",
  facebook: "https://www.facebook.com/share/19UngUaqoQ/",
  tiktok: "https://www.tiktok.com/@elegant.touch22",
} as const;

export const GOVERNORATES: { name: string; shipping: number }[] = [
  { name: "القاهرة", shipping: 40 },
  { name: "الجيزة", shipping: 40 },
  { name: "القليوبية", shipping: 45 },
  { name: "الإسكندرية", shipping: 55 },
  { name: "البحيرة", shipping: 60 },
  { name: "كفر الشيخ", shipping: 60 },
  { name: "الغربية", shipping: 55 },
  { name: "المنوفية", shipping: 50 },
  { name: "الدقهلية", shipping: 55 },
  { name: "دمياط", shipping: 60 },
  { name: "الشرقية", shipping: 55 },
  { name: "بورسعيد", shipping: 65 },
  { name: "الإسماعيلية", shipping: 60 },
  { name: "السويس", shipping: 60 },
  { name: "شمال سيناء", shipping: 80 },
  { name: "جنوب سيناء", shipping: 90 },
  { name: "الفيوم", shipping: 55 },
  { name: "بني سويف", shipping: 60 },
  { name: "المنيا", shipping: 70 },
  { name: "أسيوط", shipping: 75 },
  { name: "سوهاج", shipping: 80 },
  { name: "قنا", shipping: 85 },
  { name: "الأقصر", shipping: 90 },
  { name: "أسوان", shipping: 95 },
  { name: "البحر الأحمر", shipping: 90 },
  { name: "الوادي الجديد", shipping: 95 },
  { name: "مطروح", shipping: 80 },
];
